workspaceLocation: gitpod/gitpod-ws.code-workspace
checkoutLocation: gitpod
ports:
  - port: 1337
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
  - port: 3001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  - port: 4000
    onOpen: ignore
  # VNC
  - port: 5900
    onOpen: ignore
  # noVNC
  - port: 6080
    onOpen: ignore
  # Werft
  - port: 7777
    onOpen: ignore
  - port: 9229
    onOpen: ignore
  # Go proxy
  - port: 9999
    onOpen: ignore
  - port: 13001
    onOpen: ignore
  # Dev Theia
  - port: 13444
  # Used when using port-forwarding to SSH to preview environment VMs
  - port: 8022
    onOpen: ignore
tasks:
  - name: Setup
    init: bash setup.sh
    command: |
      gp sync-done setup
  - name: Installer dependencies
    init: |
      gp sync-await setup
      (cd install/installer && make deps)
      exit 0
  - name: Typescript
    init: |
      gp sync-await setup
      yarn --network-timeout 100000 && yarn build
      echo $?
    command: |
      gp sync-done node_modules
  - name: grpc-tools
    init: |
      gp sync-await node_modules
      curl -L https://github.com/trilogy-group/grpc-node/releases/download/v1.11.2-arm64/node-package-linux-aarch64.tar.gz -o grpc-tools.tar.gz
      cd node_modules || exit
      mkdir grpc-tools
      cd /workspace/gitpod || exit
      tar xvf grpc-tools.tar.gz -C /workspace/gitpod/node_modules/grpc-tools
    command: |
      echo "Installed grpc-tools for ARM in node_modules"
vscode:
  extensions:
    - EditorConfig.EditorConfig
    - golang.go
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - stkb.rewrap
    - zxh404.vscode-proto3
    - matthewpi.caddyfile-support
    - heptio.jsonnet
    - timonwong.shellcheck
    - fwcd.kotlin
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
