// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExtensionServiceClient is the client API for ExtensionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtensionServiceClient interface {
	// Hook point 1
	PreStartWorkspaceNotifyHook(ctx context.Context, in *PreStartWorkspaceNotifyRequest, opts ...grpc.CallOption) (*PreStartWorkspaceNotifyResponse, error)
	// Hook point 4
	PostCreateWorkspacePodModifyHook(ctx context.Context, in *PostCreateWorkspacePodModifyRequest, opts ...grpc.CallOption) (*PostCreateWorkspacePodModifyResponse, error)
	// Hook point 3
	PreStartImageBuildWorkspaceNotifyHook(ctx context.Context, in *PreStartImageBuildWorkspaceNotifyRequest, opts ...grpc.CallOption) (*PreStartImageBuildWorkspaceNotifyResponse, error)
	// Hook point 2
	PreCallImageBuilderNotifyHook(ctx context.Context, in *PreCallImageBuilderNotifyRequest, opts ...grpc.CallOption) (*PreCallImageBuilderNotifyResponse, error)
}

type extensionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionServiceClient(cc grpc.ClientConnInterface) ExtensionServiceClient {
	return &extensionServiceClient{cc}
}

func (c *extensionServiceClient) PreStartWorkspaceNotifyHook(ctx context.Context, in *PreStartWorkspaceNotifyRequest, opts ...grpc.CallOption) (*PreStartWorkspaceNotifyResponse, error) {
	out := new(PreStartWorkspaceNotifyResponse)
	err := c.cc.Invoke(ctx, "/extension_service.ExtensionService/preStartWorkspaceNotifyHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) PostCreateWorkspacePodModifyHook(ctx context.Context, in *PostCreateWorkspacePodModifyRequest, opts ...grpc.CallOption) (*PostCreateWorkspacePodModifyResponse, error) {
	out := new(PostCreateWorkspacePodModifyResponse)
	err := c.cc.Invoke(ctx, "/extension_service.ExtensionService/PostCreateWorkspacePodModifyHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) PreStartImageBuildWorkspaceNotifyHook(ctx context.Context, in *PreStartImageBuildWorkspaceNotifyRequest, opts ...grpc.CallOption) (*PreStartImageBuildWorkspaceNotifyResponse, error) {
	out := new(PreStartImageBuildWorkspaceNotifyResponse)
	err := c.cc.Invoke(ctx, "/extension_service.ExtensionService/PreStartImageBuildWorkspaceNotifyHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) PreCallImageBuilderNotifyHook(ctx context.Context, in *PreCallImageBuilderNotifyRequest, opts ...grpc.CallOption) (*PreCallImageBuilderNotifyResponse, error) {
	out := new(PreCallImageBuilderNotifyResponse)
	err := c.cc.Invoke(ctx, "/extension_service.ExtensionService/PreCallImageBuilderNotifyHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtensionServiceServer is the server API for ExtensionService service.
// All implementations must embed UnimplementedExtensionServiceServer
// for forward compatibility
type ExtensionServiceServer interface {
	// Hook point 1
	PreStartWorkspaceNotifyHook(context.Context, *PreStartWorkspaceNotifyRequest) (*PreStartWorkspaceNotifyResponse, error)
	// Hook point 4
	PostCreateWorkspacePodModifyHook(context.Context, *PostCreateWorkspacePodModifyRequest) (*PostCreateWorkspacePodModifyResponse, error)
	// Hook point 3
	PreStartImageBuildWorkspaceNotifyHook(context.Context, *PreStartImageBuildWorkspaceNotifyRequest) (*PreStartImageBuildWorkspaceNotifyResponse, error)
	// Hook point 2
	PreCallImageBuilderNotifyHook(context.Context, *PreCallImageBuilderNotifyRequest) (*PreCallImageBuilderNotifyResponse, error)
	mustEmbedUnimplementedExtensionServiceServer()
}

// UnimplementedExtensionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExtensionServiceServer struct {
}

func (UnimplementedExtensionServiceServer) PreStartWorkspaceNotifyHook(context.Context, *PreStartWorkspaceNotifyRequest) (*PreStartWorkspaceNotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreStartWorkspaceNotifyHook not implemented")
}
func (UnimplementedExtensionServiceServer) PostCreateWorkspacePodModifyHook(context.Context, *PostCreateWorkspacePodModifyRequest) (*PostCreateWorkspacePodModifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostCreateWorkspacePodModifyHook not implemented")
}
func (UnimplementedExtensionServiceServer) PreStartImageBuildWorkspaceNotifyHook(context.Context, *PreStartImageBuildWorkspaceNotifyRequest) (*PreStartImageBuildWorkspaceNotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreStartImageBuildWorkspaceNotifyHook not implemented")
}
func (UnimplementedExtensionServiceServer) PreCallImageBuilderNotifyHook(context.Context, *PreCallImageBuilderNotifyRequest) (*PreCallImageBuilderNotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreCallImageBuilderNotifyHook not implemented")
}
func (UnimplementedExtensionServiceServer) mustEmbedUnimplementedExtensionServiceServer() {}

// UnsafeExtensionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionServiceServer will
// result in compilation errors.
type UnsafeExtensionServiceServer interface {
	mustEmbedUnimplementedExtensionServiceServer()
}

func RegisterExtensionServiceServer(s grpc.ServiceRegistrar, srv ExtensionServiceServer) {
	s.RegisterService(&ExtensionService_ServiceDesc, srv)
}

func _ExtensionService_PreStartWorkspaceNotifyHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreStartWorkspaceNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).PreStartWorkspaceNotifyHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extension_service.ExtensionService/preStartWorkspaceNotifyHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).PreStartWorkspaceNotifyHook(ctx, req.(*PreStartWorkspaceNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_PostCreateWorkspacePodModifyHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCreateWorkspacePodModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).PostCreateWorkspacePodModifyHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extension_service.ExtensionService/PostCreateWorkspacePodModifyHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).PostCreateWorkspacePodModifyHook(ctx, req.(*PostCreateWorkspacePodModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_PreStartImageBuildWorkspaceNotifyHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreStartImageBuildWorkspaceNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).PreStartImageBuildWorkspaceNotifyHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extension_service.ExtensionService/PreStartImageBuildWorkspaceNotifyHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).PreStartImageBuildWorkspaceNotifyHook(ctx, req.(*PreStartImageBuildWorkspaceNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_PreCallImageBuilderNotifyHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreCallImageBuilderNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).PreCallImageBuilderNotifyHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extension_service.ExtensionService/PreCallImageBuilderNotifyHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).PreCallImageBuilderNotifyHook(ctx, req.(*PreCallImageBuilderNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtensionService_ServiceDesc is the grpc.ServiceDesc for ExtensionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtensionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "extension_service.ExtensionService",
	HandlerType: (*ExtensionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "preStartWorkspaceNotifyHook",
			Handler:    _ExtensionService_PreStartWorkspaceNotifyHook_Handler,
		},
		{
			MethodName: "PostCreateWorkspacePodModifyHook",
			Handler:    _ExtensionService_PostCreateWorkspacePodModifyHook_Handler,
		},
		{
			MethodName: "PreStartImageBuildWorkspaceNotifyHook",
			Handler:    _ExtensionService_PreStartImageBuildWorkspaceNotifyHook_Handler,
		},
		{
			MethodName: "PreCallImageBuilderNotifyHook",
			Handler:    _ExtensionService_PreCallImageBuilderNotifyHook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
