apiVersion: kots.io/v1beta1
kind: License
metadata:
  creationTimestamp: null
  name: community
spec:
  appSlug: gitpod
  channelID: 259YYBILXTa30S1Soli9YcWcPTb
  channelName: Stable
  customerName: Community
  endpoint: https://replicated.app
  entitlements:
    customerId:
      title: Customer ID
      value: ""
      valueType: String
    domain:
      title: Domain
      value: ""
      valueType: String
    expires_at:
      description: License Expiration
      title: Expiration
      value: ""
      valueType: String
    levelId:
      isHidden: true
      title: License level
      value: 1
      valueType: Integer
    seats:
      title: User seats
      value: 10
      valueType: Integer
  isGitOpsSupported: true
  isIdentityServiceSupported: true
  isSemverRequired: true
  isSnapshotSupported: true
  licenseID: 273WZe6zHEcVHGOuIAviuyGXbgm
  licenseSequence: 9
  licenseType: community
  signature: eyJsaWNlbnNlRGF0YSI6ImV5SmhjR2xXWlhKemFXOXVJam9pYTI5MGN5NXBieTkyTVdKbGRHRXhJaXdpYTJsdVpDSTZJa3hwWTJWdWMyVWlMQ0p0WlhSaFpHRjBZU0k2ZXlKdVlXMWxJam9pWTI5dGJYVnVhWFI1SW4wc0luTndaV01pT25zaWJHbGpaVzV6WlVsRUlqb2lNamN6VjFwbE5ucElSV05XU0VkUGRVbEJkbWwxZVVkWVltZHRJaXdpYkdsalpXNXpaVlI1Y0dVaU9pSmpiMjF0ZFc1cGRIa2lMQ0pqZFhOMGIyMWxjazVoYldVaU9pSkRiMjF0ZFc1cGRIa2lMQ0poY0hCVGJIVm5Jam9pWjJsMGNHOWtJaXdpWTJoaGJtNWxiRWxFSWpvaU1qVTVXVmxDU1V4WVZHRXpNRk14VTI5c2FUbFpZMWRqVUZSaUlpd2lZMmhoYm01bGJFNWhiV1VpT2lKVGRHRmliR1VpTENKc2FXTmxibk5sVTJWeGRXVnVZMlVpT2prc0ltVnVaSEJ2YVc1MElqb2lhSFIwY0hNNkx5OXlaWEJzYVdOaGRHVmtMbUZ3Y0NJc0ltVnVkR2wwYkdWdFpXNTBjeUk2ZXlKamRYTjBiMjFsY2tsa0lqcDdJblJwZEd4bElqb2lRM1Z6ZEc5dFpYSWdTVVFpTENKMllXeDFaU0k2SWlJc0luWmhiSFZsVkhsd1pTSTZJbE4wY21sdVp5SjlMQ0prYjIxaGFXNGlPbnNpZEdsMGJHVWlPaUpFYjIxaGFXNGlMQ0oyWVd4MVpTSTZJaUlzSW5aaGJIVmxWSGx3WlNJNklsTjBjbWx1WnlKOUxDSmxlSEJwY21WelgyRjBJanA3SW5ScGRHeGxJam9pUlhod2FYSmhkR2x2YmlJc0ltUmxjMk55YVhCMGFXOXVJam9pVEdsalpXNXpaU0JGZUhCcGNtRjBhVzl1SWl3aWRtRnNkV1VpT2lJaUxDSjJZV3gxWlZSNWNHVWlPaUpUZEhKcGJtY2lmU3dpYkdWMlpXeEpaQ0k2ZXlKMGFYUnNaU0k2SWt4cFkyVnVjMlVnYkdWMlpXd2lMQ0oyWVd4MVpTSTZNU3dpZG1Gc2RXVlVlWEJsSWpvaVNXNTBaV2RsY2lJc0ltbHpTR2xrWkdWdUlqcDBjblZsZlN3aWMyVmhkSE1pT25zaWRHbDBiR1VpT2lKVmMyVnlJSE5sWVhSeklpd2lkbUZzZFdVaU9qRXdMQ0oyWVd4MVpWUjVjR1VpT2lKSmJuUmxaMlZ5SW4xOUxDSnBjMGRwZEU5d2MxTjFjSEJ2Y25SbFpDSTZkSEoxWlN3aWFYTkpaR1Z1ZEdsMGVWTmxjblpwWTJWVGRYQndiM0owWldRaU9uUnlkV1VzSW1selUyNWhjSE5vYjNSVGRYQndiM0owWldRaU9uUnlkV1VzSW1selRtVjNTMjkwYzFWcFJXNWhZbXhsWkNJNmRISjFaU3dpYVhOVFpXMTJaWEpTWlhGMWFYSmxaQ0k2ZEhKMVpYMTkiLCJpbm5lclNpZ25hdHVyZSI6ImV5SnNhV05sYm5ObFUybG5ibUYwZFhKbElqb2lhMUJzSzBoT1pFMVFkakZKZEhCYVpWZDNSazgxVDBSeUwwRXJURkF5U0ROVGIzTTNjRTloVjJwblpIaGhTbFZJTnpkMmFtUlhSbXN5UldsUE1TczRlakZMTjFreGExWlhRWGRpV1ZwVllXdHdVVGREU2pkMllqSlpUREoxT0dGMk5tbDRlVUZKZVZVMmRXeFlhVXg1UjBreWRrUkpabFJCYWtwRlpra3liVGh2ZDNsWlRYVkxZMFJMWlVwYVJFTXdRMU5PVFdKdGVEVm5WVGt5VTJkSFZXaFlPVFYyY2pKME1XSk1Sa3AwTkdoblVHNDVWalpXYVZCcmJrNWFNa1ZCV0dwRmVDOUdka0Z5YmpOQk0xVTVNa05XVUhZMWNrWlZOazUxUkdKWVUyUmhUWHBLYTBSbU5uWktWVGxOUjJadmFGVnZMMHg2WmxSa2JXTlBNRXRwYlZKdVJIRm9kRWhXTUVSWWNGWnFTR1Y2Y1RsaGIzWlBOWFJVT1dKNlVpdFRTWFpzYm01VEt6VTFVeTl2UjBvNE9FTnZiVUZwUTNGWWVVVjBRbkE0VEROVmNIQnVkR1JvTlZoWFdWTkJTMGRrZEhjd00yVm5QVDBpTENKd2RXSnNhV05MWlhraU9pSXRMUzB0TFVKRlIwbE9JRkJWUWt4SlF5QkxSVmt0TFMwdExWeHVUVWxKUWtscVFVNUNaMnR4YUd0cFJ6bDNNRUpCVVVWR1FVRlBRMEZST0VGTlNVbENRMmRMUTBGUlJVRnZOVzU2T1ZsRVMxTlJSbVZ3YjJKYVZqQTVkMXh1V0V0bE4zUnNURlZWVlc1VFpUZ3dNRWREUzFSRFZGcHpibTlxZFVKaGVXcHBTMlIzV2tRelZWUktjVEJFYVc5QmNsaFZhMmhFTkd0bWRETnRSRlEzUmx4dVlrRnllRmRFVlhSck4xZHpWakZtYkVodmNHdGlXRnBJY0VoeVQzZDJXR1pUUWtoaU9WRkJhVWswZDFwRGRtbENaamRPTUhWbFRXbG9VREprYTNCc2JWeHVObVpJTHpGVGJHcGtaVlZTTVdWSmNtVldOMlJEUVhCaWFXNXlOazlVU0RGalUwNDFWbU5aZUhOMlVqaFVPVGdyVVVsSEwwWldhbU0zYTNOclNtSnlNMXh1ZDBKVGRHaGpVbGhLYmt0dFprb3plV1Z4ZDJkbE5rRkJRMmRuVjFaUVREUkdhblpvTkM5Uk1uUnhXa2RDY1d4UFdYVjRMelJJVjNaVFUyVllTMWgyY2x4dVlVUmFja05uU1hGT01YQlJSVmt3YW0weVpreEhaRTlEUldoRmRsUnhaRTQwZFc5bmJFMDFjaXN5ZFVsWWJuVkVhRW92UTNaTGRHZFRSV1pJTTNCa2RWeHVjbEZKUkVGUlFVSmNiaTB0TFMwdFJVNUVJRkJWUWt4SlF5QkxSVmt0TFMwdExWeHVJaXdpYTJWNVUybG5ibUYwZFhKbElqb2laWGxLZW1GWFpIVlpXRkl4WTIxVmFVOXBTbGRWYlZwNVZGWm5OV05yWkRKVVZGWlVXbXN4YzJNeWNFWlViazV3Vld0b1RFd3llRzVqTURGVVlWVjBhVTVYZEhWUFZYUXpWRzVXU2xWWGRHMVRNbG95VmpOc1ZWVlhTakppYTFKTFYyMVNlRTVXVm5KVmExSkRVbFZ3YVdWc2NFUlZSa3A1VWpOQk5HUlVXbmhOVm1ONVZHeFpjbFZWVG5sVlZYUktZekZSZVdNeFpFUmlWVlpzWkZWcmNsSkdXbFpOTWpsc1VtdGpNMlZFWkZSUmVrWnNZMVV4ZVdWcWFESlBXRkpMVDBVMWVtRnVUblZaTWpWRFVqTmFiRTFZYkU5alYxcDBVVEExWVZGWGNHbFZNRnBzVEhwb1UyUXdiM1pOVjJ4b1YxVk9NMWxZWXpGalF6bDVUa2QwUzJOVVVYZFZha3B0VWxaT1IxSlZXbnBSYW1oWVVsaGtXR0ZGZEhoWlZ6a3lVMnhLZVU1WFpHRlphMlJUWVVkMGRtTldiRVJYYTFaTVZrVktkVTVFYUVOaWFrcDJVVEZqY2sxV1ZuRmpla1Y0VTBad2VVNHdkRU5XYlhjelQwUnJlVlJWYkVkVVZGWm9WRzVzVDFSdVpFeGFNbXh4WWxjMVZrd3piRTlYVjJSSldXdDRVbVJIZEVsYVZGSXlWV3MxYVdWSFdrVlVWMVV4WkVWNFQxVklRVE5UVldoS1VWVldVVXd6UWxGaU0yczFaRzB4UTJSRk1XRmtlWFJWV1drNVdGbFdWbk5SVjFZMlUxaFdjbE14VlhaVWExcENWVEpuZVZKclJUbFFVMGx6U1cxa2MySXlTbWhpUlhSc1pWVnNhMGxxYjJsWmJWSnNXbFJWTWs1VVdYZFpNbHBwVGtST2FrOVhTWGxQUjBwdFQxUm9iRmxYVG1oYWJVVXlUa1JaYVdaUlBUMGlmUT09In0=
status: {}
