packages:
  - name: app
    type: yarn
    srcs:
      - "src/**"
      - package.json
    deps:
      - components/extension-service-api/typescript:lib
    config:
      packaging: offline-mirror
      yarnLock: ${coreYarnLockBase}/yarn.lock
      tsconfig: tsconfig.json
  - name: docker
    type: docker
    deps:
      - :app
    argdeps:
      - imageRepoBase
    config:
      buildArgs:
        VERSION: ${version}
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: server
      image:
        - ${imageRepoBase}/extension-service:${version}
        - ${imageRepoBase}/extension-service:commit-${__git_commit}
