apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- chartHelmSecret.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap.yaml
- daemonset.yaml
- service.yaml
- serviceaccount.yaml
- tests/test-connection.yaml
