apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
commonAnnotations:
  kots.io/app-slug: gitpod
kind: Kustomization
patchesStrategicMerge:
- pullsecrets.yaml
resources:
- secret.yaml
transformers:
- backup-label-transformer.yaml
