---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    app: gitpod
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.4
    component: gitpod-log-collector
    helm.sh/chart: fluent-bit-0.20.2
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gitpod-registry
---
apiVersion: v1
kind: Pod
metadata:
  name: fluent-bit-test-connection
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.4
    helm.sh/chart: fluent-bit-0.20.2
spec:
  imagePullSecrets:
  - name: gitpod-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: installation-status
  labels:
    app: gitpod
    component: gitpod-installer-status
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gitpod-registry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: installer-24
  labels:
    app: gitpod
    component: gitpod-installer
    cursor: "24"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gitpod-registry
