# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

# This exists as debug information for the support bundle
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitpod-installation
  labels:
    app: gitpod
    component: gitpod-installer
data:
  channelName: "Stable"
  cursor: "24"
  isAirgap: "false"
  releaseNotes: "## October 2022 hotfix release of the Gitpod Installer\n\nDocker image: `eu.gcr.io/gitpod-core-dev/build/installer:release-2022.10.2.1`\n\nRefer to the [self-hosted documentation](https://www.gitpod.io/docs/self-hosted/latest) to know more about how to setup Gitpod.\n\n## What's Changed\n* [kots] merge custom docker config correctly by @Pothulapati https://github.com/gitpod-io/gitpod/pull/14432\n* [kots]: set emptyDir and allow timeout configuration by @MrSimonEmms https://github.com/gitpod-io/gitpod/pull/14500\n\n**Full Changelog**: https://github.com/gitpod-io/gitpod/compare/2022.10.0...2022.10.2-rc0"
  sequence: "5"
  version: "2022.10.2"
