# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: v1
kind: Secret
metadata:
  name: storage-s3
  labels:
    app: gitpod
    component: gitpod-installer
  annotations:
    kots.io/when: 'true'
data:
  accessKeyId: 'QUtJQVZCUjRNSUdCWVNYSVFHN00='
  secretAccessKey: 'cHd2SXc2bnZRTldwYTU5b0pIQnI2b25mMUN0ZlNLVDgyYjZLMFA1eQ=='
