apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- charts/fluent-bit/chartHelmSecret.yaml
- charts/fluent-bit/clusterrole.yaml
- charts/fluent-bit/clusterrolebinding.yaml
- charts/fluent-bit/configmap.yaml
- charts/fluent-bit/daemonset.yaml
- charts/fluent-bit/service.yaml
- charts/fluent-bit/serviceaccount.yaml
- charts/fluent-bit/tests/test-connection.yaml
- gitpod-certificate.yaml
- gitpod-installation-status.yaml
- gitpod-installation.yaml
- gitpod-installer-job.yaml
- gitpod-kots-config.yaml
- gitpod-license.yaml
- gitpod-storage-s3-secret.yaml
