# * we have to run the extension service as a pod. For that we need this deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod-infra-hybrid
# * labels
  labels:
    app: gitpod
    app.kubernetes.io/name: extension-service
    component: extension-service
  name: extension-service
  namespace: gitpod-infra-hybrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitpod
      component: extension-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitpod
        component: extension-service
      name: extension-service
      namespace: gitpod-infra-hybrid
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gitpod.io/workload_workspace_regular
                operator: Exists
      containers:
        - image: 346945241475.dkr.ecr.us-east-1.amazonaws.com/gitpod-infra-test/extension-service:arm-support
          imagePullPolicy: Always
          name: extension-service
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: mysql-root-password
                optional: false
          - name: PRISMA_DB_URL
            value: mysql://root:$(DB_PASSWORD)@mysql.gitpod-infra-hybrid.svc.cluster.local:3306/extensionservice
          # * change resources accordingly
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
